
const LEVEL_1_TIME = 60;
const LEVEL_2_TIME = 50;
const LEVEL_3_TIME = 45;
const LEVEL_4_TIME = 40;
const LEVEL_5_TIME = 40;

const TIME_FOR_LEVELS = [LEVEL_1_TIME,LEVEL_2_TIME,LEVEL_3_TIME,LEVEL_4_TIME,LEVEL_5_TIME]



export {LEVEL_1_TIME,LEVEL_2_TIME,LEVEL_3_TIME,LEVEL_4_TIME,LEVEL_5_TIME,TIME_FOR_LEVELS};  